<?php

// Get payment URL response
$arrResponse = $block->getFormPaycometUrl();

if (!filter_var($arrResponse["url"], FILTER_VALIDATE_URL)) {
    $action == "";
} else {
    $action = $arrResponse["url"];
}

?>

<html>
<head>
</head>
<body>

<form id="paycomet_form" method="POST" action="<?= /* @noEscape */ $action; ?>"></form>

<?php if ($action == ""): ?>
    <p><?= /* @noEscape */ __('Error') . ": " . /* @noEscape */ $arrResponse["error"];?></p>
<?php else: ?>
    <script>
        document.getElementById('paycomet_form').submit();
    </script>
<?php endif; ?>

</body>
</html>