<?php
$_cards = $block->getPaycometCards();

?>

<p><?php echo $block->escapeHtml(
    __('In this section you can Edit or Delete your stored cards or Add a new one to your account')
); ?></p>
<form class="form-paycometcards-items" id="paycometcards-view-form" action="<?php /* @escapeNotVerified */ echo $block->getUrl('paycomet_payment/cards/remove') ?>" method="post">

<div id="cards" class="table-wrapper">
    <table class="data table table-order-items paycomet-cards" id="paycomet-cards-table">
        <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('PAYCOMET Cards') ?></caption>
        <thead>
            <tr>
                <th scope="col" class="col number"><?php /* @escapeNotVerified */ echo __('Number') ?></th>
                <th scope="col" class="col brand"><?php /* @escapeNotVerified */ echo __('Brand') ?></th>
                <th scope="col" class="col expirty"><?php /* @escapeNotVerified */ echo __('Expiry Date') ?></th>
                <th scope="col" class="col description"><?php /* @escapeNotVerified */ echo __('Description') ?></th>
                <th scope="col" class="col actions">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($_cards as $_card): ?>
                <tr>
                    <td data-th="<?php echo $block->escapeHtml(__('Number')) ?>" class="col number"><?php /* @escapeNotVerified */  echo $_card["cc"];?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Brand')) ?>" class="col number"><?php /* @escapeNotVerified */  echo $_card["brand"];?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Expiry Date')) ?>" class="col number"><?php /* @escapeNotVerified */  echo $_card["expiry"];?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Description')) ?>" class="col description"><input type="text" maxlength="64" id="card_desc_<?php echo $_card["hash"];?>" name="card_desc_[<?php echo $_card["hash"];?>]" value="<?php /* @escapeNotVerified */ print $_card["desc"];?>" placeholder="añada una descripción"></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        
                        <a href="#" data-role="update" data-post='<?php /* @escapeNotVerified */ echo $block->getUpdateParams($_card["hash"]) ?>' title="<?php /* @escapeNotVerified */ echo __('Update Description') ?>" class="btn-remove action delete">
						    <span><?php /* @escapeNotVerified */ echo __('Update Description');?></span>
						</a>
						<a href="#" data-role="remove" data-post='<?php /* @escapeNotVerified */ echo $block->getRemoveParams($_card["hash"]) ?>' title="<?php /* @escapeNotVerified */ echo __('Remove Card') ?>" class="btn-remove action delete">
						    <span><?php /* @escapeNotVerified */ echo __('Remove Card');?></span>
						</a>
                        
                     </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
</form>


<div id="paycomet-cards" data-bind="scope:'paycomet-cards'" >
    <!-- ko template: getTemplate() --><!-- /ko -->
<script type="text/x-magento-init">
       {
           "#paycomet-cards": {
               "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
           }
       }
</script>
<input type="hidden" id="paycomet-iframe" value="<?php echo $block->escapeHtml($block->getIframeUrl());?>" />
</div>
