<?php
/** @var \Paycomet\Payment\ViewModel\Apm\Instantcredit\OddSimulatorViewModel $viewModel */
$viewModel = $block->getViewModel();
$icHelper = $viewModel->getIcHelper();

// If APM InstantCredit not enable, return
if (!$icHelper->getIsEnabled()) return;

?>
<script>
    require([
        'jquery',
        'domReady',
        '<?= $viewModel->getSimulatorUrl() ?>'
    ], function($){
        $(function(){
            window.hashIcSimulator = "<?= $viewModel->getHash() ?>";
            window.icSimulatorCustom = {
                upperLimit:  <?= $icHelper->getUpperLimit() ?>,
                lowerLimit: <?= $icHelper->getLowerLimit() ?>,
            };

            // Fire event manually (cause in RequireJS is not fired)
            document.dispatchEvent(new Event('DOMContentLoaded'));
        });
    });
</script>