<?php
/** @var \Paycomet\Payment\ViewModel\Apm\Instantcredit\OddSimulatorViewModel $viewModel */
$viewModel = $block->getViewModel();
$icHelper = $viewModel->getIcHelper();

if (!$icHelper->getIsEnabled()) {
    return;
}

?>
<script>
    require([
        'jquery',
        'domReady',
        '<?= /* @noEscape */ $viewModel->getSimulatorUrl() ?>'
    ], function($){
        $(function(){
            window.hashIcSimulator = "<?= /* @noEscape */ $viewModel->getHash() ?>";
            window.icSimulatorCustom = {
                upperLimit:  <?= /* @noEscape */ $icHelper->getUpperLimit() ?>,
                lowerLimit: <?= /* @noEscape */ $icHelper->getLowerLimit() ?>,
            };

            // Fire event manually (cause in RequireJS is not fired)
            document.dispatchEvent(new Event('DOMContentLoaded'));
        });
    });
</script>