<?php
/**
 * @see \Magento\Payment\Block\Info
 */
?>
<?=$block->escapeHtml($block->getMethod()->getTitle());
$specificInfo = $block->getSpecificInformation();
?>
    <table class="data-table admin__table-secondary">
        <?php foreach ($specificInfo as $label => $value): ?>
          <tr>
              <th><?=$block->escapeHtml($label)?>:</th>
              <td>
                    <?= /* @noEscape */ nl2br(
                        $block->escapeHtml(
                            implode("\n", $block->getValueAsArray($value, true))
                        )
                    );?>
              </td>
          </tr>
        <?php endforeach; ?>
    </table>
<?=$block->getChildHtml()?>
