<?php if ($block->getCode() == "paycomet_multibanco"):?> 
<div class="block block-paycomet-information">
    <div class="block-title">
        <strong><?= /* @noEscape */ $block->getData('title');?></strong>
    </div>
    <div class="block-content">
        <span class="paycoment-icon-left">
            <img class="payment-icon" src="<?= /* @noEscape */ $block->getData('img_src');?>" 
            title="<?= /* @noEscape */ $block->getData('title');?>">
        </span>
        <span>
            <strong><?= /* @noEscape */__("Entity");?>:</strong>  <?= /* @noEscape */ $block->getData('Entity');?>
            <br/>
            <strong><?= /* @noEscape */__("Reference");?>:</strong> <?= /* @noEscape */ $block->getData('Reference');?>
        </span>
    </div>
</div>
<?php endif ?>
